### ISSUE TITLE
library load failed after install

### ISSUE THREAD

**Issue by zhcui** [pyscf/shciscf#5]
Hi all,

I followed the installation (for my locally installed pyscf) in the README.
However, an error occurred:
Traceback (most recent call last):
  File "hChain.py", line 3, in <module>
    from pyscf.shciscf import shci
  File "/home/zhcui/program/shciscf/pyscf/shciscf/shci.py", line 64, in <module>
    shciLib = load_library("libshciscf")
  File "/home/zhcui/program/pyscf_ZHC_kpt_symm/pyscf/lib/misc.py", line 53, in load_library
    return numpy.ctypeslib.load_library(libname, _loaderpath)
  File "/home/zhcui/program/anaconda3_new/lib/python3.8/site-packages/numpy/ctypeslib.py", line 155, in load_library
    raise OSError("no file with expected extension")
OSError: no file with expected extension

Could you take a look? Thanks!

Best,
Zhihao

**Comment by sunqm** [comment]
Where was the pyscf core module installed? Do you find libshci.so under `/home/zhcui/program/shciscf/pyscf/lib` ?

**Comment by jiangtong1000** [comment]
Hi, I met this issue too. There is no `.so` file in both `/path-to/shciscf/pyscf/lib` and `/path-to/shciscf/pyscf/shciscf`.

**Comment by jiangtong1000** [comment]
worked around it by `cp ~/.local/lib/python3.8/site-packages/pyscf/lib/libshciscf.so /path-to/pyscf/pyscf/lib/`
